#=================================================================================================
# Config file to train Meta-Learning algorithm
#=================================================================================================

RANDOM_SEED: 1979

# -------------------------------------------------------------------------
# TRAINING META-LEARNING ALGORITHM
# -------------------------------------------------------------------------
PARAMS_MODEL:
  MODEL: 'matching' # matching, prototypical or relation
  TRAINING: 'episodic' # classical or episodic
  N_WORKERS: 28
  N_WAY: 20
  N_SHOT: 5
  N_QUERY: 1
  N_TASKS: 100
  N_EPOCHS: 20 
  EARLY_STOP_THRESH: 10
  SCHEDULER_FACTOR: 0.1
  SCHEDULER_PATIENCE: 5
  LEARNING_RATE: 0.000028
  VALIDATION: True
  PRETRAINED: True
  # Measurements 
  TENSORBOARD: False
  ENERGY_CONSUMPTION: False
  # Audio preprocessing
  HPSS: True
  REMOVE_BG: False

# -------------------------------------------------------------------------
# META EMBEDDED CLUSTERING
# -------------------------------------------------------------------------
  FEATURE_EXTRACTOR: 'models/matching-networks-20way-5shot-episodic.pt'
  N_ITERATIONS: 20
  AUGMENTATION: False