#=================================================================================================
#
# Config file to train Few-Shot Learning (FSL) algorithms
#
#=================================================================================================

RANDOM_SEED: 1979                # Fixed random seed

################################
# TRAINING FEW-SHOT CLASSIFIER
################################
PARAMS_MODEL:
  DEVICE: "cpu"
  BATCH_SIZE: 128
  N_WORKERS: 0
  N_WAY: 5
  N_SHOT: 5
  N_QUERY: 1
  N_TASKS: 100
  N_EPOCHS: 200
  EARLY_STOP_THRESH: 10
  SCHEDULER_FACTOR: 0.1
  SCHEDULER_PATIENCE: 5
  LEARNING_RATE: 0.0001
  TRAINING: "episodic"  # classical or episodic
  PRETRAINED: True
  # Audio preprocess
  HPSS: True
  REMOVE_BG: False
  # Few-Shot Classifier 
  MODEL: 'prototypical'  # matching, prototypical or relation
